//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () { function o(n) { var i = e; n &amp;&amp; (e[n] || (e[n] = {}), i = e[n]); if (!i.define || !i.define.packaged) t.original = i.define, i.define = t, i.define.packaged = !0; if (!i.require || !i.require.packaged) r.original = i.require, i.require = r, i.require.packaged = !0 } var ACE_NAMESPACE = &quot;&quot;, e = function () { return this }(); !e &amp;&amp; typeof window != &quot;undefined&quot; &amp;&amp; (e = window); if (!ACE_NAMESPACE &amp;&amp; typeof requirejs != &quot;undefined&quot;) return; var t = function (e, n, r) { if (typeof e != &quot;string&quot;) { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ace {
            get {
                return ResourceManager.GetString("ace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG {
            get {
                object obj = ResourceManager.GetObject("BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Connections {
            get {
                object obj = ResourceManager.GetObject("Connections", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel {
            get {
                object obj = ResourceManager.GetObject("Excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to define(&quot;ace/snippets&quot;,[&quot;require&quot;,&quot;exports&quot;,&quot;module&quot;,&quot;ace/lib/oop&quot;,&quot;ace/lib/event_emitter&quot;,&quot;ace/lib/lang&quot;,&quot;ace/range&quot;,&quot;ace/anchor&quot;,&quot;ace/keyboard/hash_handler&quot;,&quot;ace/tokenizer&quot;,&quot;ace/lib/dom&quot;,&quot;ace/editor&quot;],function(e,t,n){&quot;use strict&quot;;var r=e(&quot;./lib/oop&quot;),i=e(&quot;./lib/event_emitter&quot;).EventEmitter,s=e(&quot;./lib/lang&quot;),o=e(&quot;./range&quot;).Range,u=e(&quot;./anchor&quot;).Anchor,a=e(&quot;./keyboard/hash_handler&quot;).HashHandler,f=e(&quot;./tokenizer&quot;).Tokenizer,l=o.comparePoints,c=function(){this.snippetMap={},this.snippetNameMap={}};(function(){ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ext_language_tools {
            get {
                return ResourceManager.GetString("ext_language_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimize {
            get {
                object obj = ResourceManager.GetObject("Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to define(&quot;ace/mode/doc_comment_highlight_rules&quot;, [&quot;require&quot;, &quot;exports&quot;, &quot;module&quot;, &quot;ace/lib/oop&quot;, &quot;ace/mode/text_highlight_rules&quot;], function (e, t, n) { &quot;use strict&quot;; var r = e(&quot;../lib/oop&quot;), i = e(&quot;./text_highlight_rules&quot;).TextHighlightRules, s = function () { this.$rules = { start: [{ token: &quot;comment.doc.tag&quot;, regex: &quot;@[\\w\\d_]+&quot; }, s.getTagRule(), { defaultToken: &quot;comment.doc&quot;, caseInsensitive: !0 }] } }; r.inherits(s, i), s.getTagRule = function (e) { return { token: &quot;comment.doc.tag.storage.type&quot;, regex: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mode_sqlserver {
            get {
                return ResourceManager.GetString("mode_sqlserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New_Excel {
            get {
                object obj = ResourceManager.GetObject("New_Excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ProgIco {
            get {
                object obj = ResourceManager.GetObject("ProgIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProgLogo {
            get {
                object obj = ResourceManager.GetObject("ProgLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0014)about:internet --&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Query&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            margin: 0;
        ///        }
        ///
        ///        pre {
        ///            margin: 0;
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;script src=&quot;ace.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;theme-sqlserver.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;mode-sqlserver.js&quot;&gt;&lt;/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryPage {
            get {
                return ResourceManager.GetString("QueryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shutdown {
            get {
                object obj = ResourceManager.GetObject("Shutdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Snippet {
            get {
                object obj = ResourceManager.GetObject("Snippet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0014)about:internet --&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Query&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            margin: 0;
        ///        }
        ///        
        ///        pre {
        ///            margin: 0;
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;script src=&quot;ace.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;theme-sqlserver.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;mode-sqlserv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SnippetPage {
            get {
                return ResourceManager.GetString("SnippetPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to define(&quot;ace/snippets/sqlserver&quot;,[&quot;require&quot;,&quot;exports&quot;,&quot;module&quot;], function(require, exports, module) {
        ///&quot;use strict&quot;;
        ///exports.snippetText = readTextFile(&quot;sqlserver.snippets&quot;);
        ///exports.scope = &quot;sqlserver&quot;;
        ///});
        ///
        ///function readTextFile(p) { var x = &quot;&quot;; var f = new XMLHttpRequest(); f.open(&quot;GET&quot;, p, false); f.onreadystatechange = function () { if (f.readyState === 4) { if (f.status === 200 || f.status === 0) { x = f.responseText; } } }; f.send(null); return x; }.
        /// </summary>
        internal static string snippets_sqlserver {
            get {
                return ResourceManager.GetString("snippets_sqlserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to define(&quot;ace/theme/sqlserver&quot;,[&quot;require&quot;,&quot;exports&quot;,&quot;module&quot;,&quot;ace/lib/dom&quot;],function(e,t,n){t.isDark=!1,t.cssClass=&quot;ace-sqlserver&quot;,t.cssText=&apos;.ace-sqlserver .ace_gutter {background: #ebebeb;color: #333;overflow: hidden;}.ace-sqlserver .ace_print-margin {width: 1px;background: #e8e8e8;}.ace-sqlserver {background-color: #FFFFFF;color: black;}.ace-sqlserver .ace_identifier {color: black;}.ace-sqlserver .ace_keyword {color: #0000FF;}.ace-sqlserver .ace_numeric {color: black;}.ace-sqlserver .ace_storage {color: #1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string theme_sqlserver {
            get {
                return ResourceManager.GetString("theme_sqlserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Update_Excel {
            get {
                object obj = ResourceManager.GetObject("Update_Excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
