version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
init:
  - ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200`tapi.nuget.org")'
before_build:
  - nuget restore
cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache
